source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'BaiduMeetsReactNative' do
  react_native_path = "../node_modules/react-native"
  pod 'Yoga', :path => "#{react_native_path}/ReactCommon/yoga"
  pod 'React', :path => react_native_path
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'DevSupport'
  ]
  pod 'BaiduMapKit'
end


